-- Datenbankschema für die E-Mobility-Webanwendung
-- PostgreSQL-kompatible Definition der Tabellen, Primärschlüssel,
-- Fremdschlüssel, Unique-Constraints und Indizes.

CREATE TABLE IF NOT EXISTS users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(80)  NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL DEFAULT 'rider',
    payment_method  VARCHAR(120),
    api_token       VARCHAR(64)  NOT NULL UNIQUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('rider', 'provider'))
);

CREATE TABLE IF NOT EXISTS vehicles (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       VARCHAR(32)  NOT NULL UNIQUE,
    name            VARCHAR(120) NOT NULL,
    vehicle_type    VARCHAR(20)  NOT NULL DEFAULT 'e_scooter',
    battery_level   INTEGER      NOT NULL DEFAULT 100,
    latitude        NUMERIC(9,6) NOT NULL,
    longitude       NUMERIC(9,6) NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'available',
    unlock_code     VARCHAR(32)  NOT NULL,
    provider_id     INTEGER      NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicles_provider
        FOREIGN KEY (provider_id)
        REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_vehicles_vehicle_type CHECK (vehicle_type IN ('e_scooter', 'e_bike', 'e_cargo')),
    CONSTRAINT chk_vehicles_status CHECK (status IN ('available', 'rented', 'maintenance')),
    CONSTRAINT chk_vehicles_battery CHECK (battery_level BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS rentals (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id        INTEGER       NOT NULL,
    rider_id          INTEGER       NOT NULL,
    start_time        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time          TIMESTAMP WITH TIME ZONE,
    start_km          NUMERIC(10,2) NOT NULL DEFAULT 0,
    end_km            NUMERIC(10,2),
    start_latitude    NUMERIC(9,6)  NOT NULL,
    start_longitude   NUMERIC(9,6)  NOT NULL,
    end_latitude      NUMERIC(9,6),
    end_longitude     NUMERIC(9,6),
    base_price        NUMERIC(10,2) NOT NULL DEFAULT 1.50,
    price_per_minute  NUMERIC(10,2) NOT NULL DEFAULT 0.35,
    total_price       NUMERIC(10,2),
    distance_km       NUMERIC(10,2),
    status            VARCHAR(20)   NOT NULL DEFAULT 'active',
    CONSTRAINT fk_rentals_vehicle
        FOREIGN KEY (vehicle_id)
        REFERENCES vehicles(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_rentals_rider
        FOREIGN KEY (rider_id)
        REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_rentals_status CHECK (status IN ('active', 'completed')),
    CONSTRAINT chk_rentals_km CHECK (end_km IS NULL OR end_km >= start_km),
    CONSTRAINT chk_rentals_price CHECK (base_price >= 0 AND price_per_minute >= 0)
);

CREATE INDEX IF NOT EXISTS idx_vehicles_provider_id ON vehicles(provider_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status);
CREATE INDEX IF NOT EXISTS idx_rentals_vehicle_id ON rentals(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_rentals_rider_id ON rentals(rider_id);
CREATE INDEX IF NOT EXISTS idx_rentals_status ON rentals(status);

-- Beispielabfragen zur Prüfung:
-- SELECT * FROM users;
-- SELECT * FROM vehicles;
-- SELECT * FROM rentals;
